/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: f103d0d6947e92f53f1c4ba8d54acaa6)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "Scheduler" | "Stateful" | "Chat" | "Rpc";
  }
  interface Env {
    OPENAI_API_KEY: string;
    Scheduler: DurableObjectNamespace<import("./src/server").Scheduler>;
    Stateful: DurableObjectNamespace<import("./src/server").Stateful>;
    Chat: DurableObjectNamespace<import("./src/server").Chat>;
    Rpc: DurableObjectNamespace<import("./src/server").Rpc>;
    ASSETS: Fetcher;
  }
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv
    extends StringifyValues<Pick<Cloudflare.Env, "OPENAI_API_KEY">> {}
}
