/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: fd625e36bf3c511606c165004fcd35ee)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
		durableNamespaces: "CodeGeneratorAgent" | "UserAppSandboxService" | "DORateLimitStore";
	}
	interface Env {
		VibecoderStore: KVNamespace;
		ENVIRONMENT: "production";
		LOG_LEVEL: "info";
		TEMPLATES_REPOSITORY: "https://github.com/cloudflare/vibesdk-templates";
		ALLOWED_EMAIL: "";
		DISPATCH_NAMESPACE: "vibesdk-default-namespace";
		ENABLE_READ_REPLICAS: "true";
		CLOUDFLARE_AI_GATEWAY: "vibesdk-gateway";
		CUSTOM_DOMAIN: "";
		MAX_SANDBOX_INSTANCES: "10";
		SANDBOX_INSTANCE_TYPE: "standard-3";
		USE_CLOUDFLARE_IMAGES: "";
		GITHUB_OWNER: "your-org";
		GITHUB_REPO: "core-vibe-hq";
		GITHUB_API_KEY: "";
		CORE_GITHUB_API: "https://api.github.com";
		CORE_GITHUB_API_URL: "https://core-github-api.hacolby.workers.dev";
		HEALTH_WORKER_TARGETS?: string;
		WORKER_NAME?: string;
		WORKER_TYPE?: string;
		GITHUB_WORKER_API_KEY: string;
		CodeGenObject: DurableObjectNamespace<import("./worker/index").CodeGeneratorAgent>;
		Sandbox: DurableObjectNamespace<import("./worker/index").UserAppSandboxService>;
		DORateLimitStore: DurableObjectNamespace<import("./worker/index").DORateLimitStore>;
		TERMINAL_SERVER: DurableObjectNamespace<import("./worker/index").TerminalServer>;
		OPS_MONITOR_BROADCAST: DurableObjectNamespace<import("./worker/index").OpsMonitorBroadcastServer>;
		TEMPLATES_BUCKET: R2Bucket;
		DB_OPS: D1Database;
		DB_PROJECTS: D1Database;
		DB_CHATS: D1Database;
		DB_HEALTH: D1Database;
		CONFLICT_SPECIALIST: Fetcher /* ops-conflict-specialist */;
		DELIVERY_REPORT_SPECIALIST: Fetcher /* ops-delivery-report-specialist */;
		AI: Ai;
		CF_VERSION_METADATA: WorkerVersionMetadata;
		ASSETS: Fetcher;
	}
}
interface Env extends Cloudflare.Env {}
