/**
 * Worker type definitions
 * 
 * The Env interface is declared globally in worker-configuration.d.ts
 * via: interface Env extends Cloudflare.Env {}
 * 
 * This file provides a convenient import point for the Env type
 * to ensure consistent typing across the worker codebase.
 * 
 * Since Env is declared globally, we reference it here for explicit imports.
 */

import type { CoreEnv } from '@shared/types/env'

// Reference the globally declared Env interface
// This works because worker-configuration.d.ts declares: interface Env extends Cloudflare.Env {}
// TypeScript will automatically make this available in the global scope
// Note: DB_OPS, DB_PROJECTS, DB_CHATS, DB_HEALTH are defined in Cloudflare.Env via wrangler types
// Orchestrator's Env extends both Cloudflare.Env (for DB bindings) and CoreEnv (for shared types)
export interface Env extends Cloudflare.Env, Omit<CoreEnv, 'DB_OPS' | 'DB_PROJECTS' | 'DB_CHATS' | 'DB_HEALTH'> {
  // Database bindings come from Cloudflare.Env (generated by wrangler types)
  // DB_OPS, DB_PROJECTS, DB_CHATS, DB_HEALTH are automatically available
  
  // Additional orchestrator-specific bindings
  CONFLICT_SPECIALIST?: Fetcher
  DELIVERY_REPORT_SPECIALIST?: Fetcher
}

